### ISSUE TITLE
plugin doesn't inject sprite with Vite 5.2

### ISSUE THREAD

**Issue by dlohvinov** [meowtec/vite-plugin-svg-sprite#23]
Hi!

I'm having an issue using VitePluginSvgSprite with latest (5.2) Vite version. When I run `vite` (local dev mode) - everything works fine, but when I'm running `vite build && vite preview` - plugin does not inject icon sprite to index.html

Reproduction link:
https://codesandbox.io/p/devbox/svg-sprite-with-vite-5-2-8z85wr

For now, I've downgraded to vite 5.1 :(

**Comment by ridgehkr** [comment]
Can confirm that this is broken as of 5.2.0-beta.0. Imported SVGs are not included in the build. I'm not certain, but I suspect it's due to them being considered "unused" by the built-in asset plugin and pruned from the build output. If that's the case, I believe [this PR](https://github.com/vitejs/vite/pull/16087) may be the culprit.

**Comment by meowtec** [comment]
Please try v0.5.2
